name = "LAPACKExtensions"
uuid = "5987549c-6cd9-4e0c-b58b-938f5b2a1ac4"
authors = ["Aravindh Krishnamoorthy <aravindh.krishnamoorthy@fau.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
