using LinearAlgebra
using BenchmarkTools

for N in [8, 64, 1000]
    # Real
    println("$N: Real/No structure")
    X = randn(N,N)
    @btime sqrt($X)
    @btime MatrixAlgorithms.sqrtm($X)
    X1 = MatrixAlgorithms.sqrtm(X)
    display(norm(X1*X1-X))
    println("$N: Real/Symmetric")
    @btime sqrt($X+$X')
    @btime MatrixAlgorithms.sqrtm($X+$X')
    X1 = MatrixAlgorithms.sqrtm(X+X')
    display(norm(X1*X1-X-X'))
    println("$N: Real/No structure/PD")
    @btime sqrt($X+$N*I($N))
    @btime MatrixAlgorithms.sqrtm($X+$N*I($N))
    X1 = MatrixAlgorithms.sqrtm(X+N*I(N))
    display(norm(X1*X1-X-N*I(N)))
    println("$N: Real/Symmetric/PD")
    @btime sqrt($X+$X'+$N*I($N))
    @btime MatrixAlgorithms.sqrtm($X+$X'+$N*I($N))
    X1 = MatrixAlgorithms.sqrtm(X+X'+N*I(N))
    display(norm(X1*X1-X-X'-N*I(N)))
    # Complex
    println("$N: Complex/No structure")
    X = complex.(randn(N,N),randn(N,N))
    @btime sqrt($X)
    @btime MatrixAlgorithms.sqrtm($X)
    X1 = MatrixAlgorithms.sqrtm(X)
    display(norm(X1*X1-X))
    println("$N: Complex/Hermitian")
    @btime sqrt($X+$X')
    @btime MatrixAlgorithms.sqrtm($X+$X')
    X1 = MatrixAlgorithms.sqrtm(X+X')
    display(norm(X1*X1-X-X'))
    println("$N: Complex/No structure/PD")
    @btime sqrt($X+$N*I($N))
    @btime MatrixAlgorithms.sqrtm($X+$N*I($N))
    X1 = MatrixAlgorithms.sqrtm(X+N*I(N))
    display(norm(X1*X1-X-N*I(N)))
    println("$N: Complex/Hermitian/PD")
    @btime sqrt($X+$X'+$N*I($N))
    @btime MatrixAlgorithms.sqrtm($X+$X'+$N*I($N))
    X1 = MatrixAlgorithms.sqrtm(X+X'+N*I(N))
    display(norm(X1*X1-X-X'-N*I(N)))
end
